[package]
name = "cdk-ffi-python"
edition = "2021"
rust-version = "1.85.0"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/cashubtc/cdk"
repository = "https://github.com/cashubtc/cdk.git"
version = "0.18.0"
readme = "README.md"

[lib]
crate-type = ["cdylib"]
name = "cdk_ffi_python"

[[bin]]
name = "uniffi-bindgen-python"
path = "uniffi-bindgen.rs"

[dependencies]
cdk-ffi = { version = "=0.18.0", default-features = false, features = ["npubcash", "nwc", "bip353"] }
uniffi = { version = "0.30", features = ["cli"] }

[lints]


[profile.release]
lto = true
codegen-units = 1
